ext.postBuildExtras = {
    android {
        kotlinOptions {
            freeCompilerArgs += ["-Xskip-metadata-version-check"]
        }
    }
    tasks.matching { it.name.toLowerCase().endsWith("kotlin") }.all {
        kotlinOptions {
            freeCompilerArgs += ["-Xskip-metadata-version-check"]
        }
    }
}
